dist: trusty
sudo: false
language: node_js

node_js:
  - "node"
  - "10"

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm test -- test/unit/