dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: "node"
    - node_js: "10"
    - node_js: "9"
    - node_js: "8"

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm test -- test/unit/