dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: "node"
    - node_js: "10"
    - node_js: "9"
      env: NODE_FLAGS=--harmony_promise_finally
    - node_js: "8"
      env: NODE_FLAGS=--harmony_promise_finally

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm test -- test/unit/ $NODE_FLAGS